import discord
from discord.ext import commands
import config
import youtube_dl
import asyncio

# Assuming client, queue, play_music, and viewqueue are defined in this file
# client = ...
# queue = ...
# async def play_music(ctx): ...
# async def viewqueue(ctx): ...